hostname: Edge22
ip_routing: true
vrfs:
- name: VRF_A
  ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Edge-22_lo10
  shutdown: false
  ip_address: 192.168.0.22/32
ethernet_interfaces:
- name: Ethernet1
  peer: Leaf22
  type: routed
  shutdown: false
  mtu: 1500
  ospf_area: 0
  ospf_network_point_to_point: true
  vrf: VRF_A
  ip_address: 192.22.34.1/24
- name: Ethernet2
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.22.25.1/24
- name: Ethernet3
  peer: ISP-2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.22.26.1/24
- name: Ethernet4
  peer: Leaf21
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.22.33.1/24

router_bgp:
  as: 65000
  router_id: 192.168.0.22
  neighbors:
    - ip_address: 192.22.34.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.22.25.2
      remote_as:  65202
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.22.26.2
      remote_as:  65203 
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.22.25.2
        activate: true
      - ip_address: 192.22.26.2
        activate: true
    networks: 
      - prefix: 192.168.0.22/32
  redistribute_routes:
    - source_protocol: connected
  vrfs:
    - name: VRF_A
      redistribute_routes:
        - source_protocol: connected
        - source_protocol: ospf



router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.10
      vrf: VRF_A
      redistribute:
        bgp: