hostname: Edge23
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback10
  description: Edge-23_lo10
  shutdown: false
  ip_address: 192.168.0.23/32
ethernet_interfaces:
- name: Ethernet1
  peer: H23
  type: routed
  shutdown: false
  mtu: 1500
  vrf: VRF_A
  ip_address: 172.16.23.254/24
- name: Ethernet2
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.23.25.1/24
- name: Ethernet3
  peer: ISP-2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.23.26.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.23
  neighbors:
    - ip_address: 192.23.25.2
      remote_as:  65202
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.23.26.2
      remote_as:  65203
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.23.25.2
        activate: true
      - ip_address: 192.23.26.2
        activate: true
    networks: 
      - prefix: 192.168.0.23/32
      - prefix: 172.16.23.0/24

