hostname: Edge21
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Edge-21_lo10
  shutdown: false
  ip_address: 192.168.0.21/32
ethernet_interfaces:
- name: Ethernet1
  peer: Edge20
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet2
  peer: Edge20
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet3
  peer: Leaf21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.21.33.1/24
- name: Ethernet4
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.21.25.1/24
- name: Ethernet5
  peer: ISP-2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.21.26.1/24
- name: Ethernet6
  peer: Leaf22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.21.34.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.21
  neighbors:
    - ip_address: 192.21.25.2
      remote_as:  65202
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.21.26.2
      remote_as:  65203
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.21.25.2
        activate: true
      - ip_address: 192.21.26.2
        activate: true
    networks: 
      - prefix: 192.168.0.21/32
  redistribute_routes:
    - source_protocol: connected
  vrfs:
        - name: VRF_A
          neighbors:
            - ip_address: 192.21.33.2
              remote_as:  65000
              allowas_in:
                enabled: true
                times: 6
          address_family_ipv4:
            neighbors:
            - ip_address:  192.21.33.2
              activate: true  
            networks: 
            - prefix: 192.168.0.21/32
            redistribute_routes:
            - source_protocol: connected        
          networks: 
            - prefix: 192.168.0.21/32


