hostname: Edge14
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
- name: Loopback10
  description: Edge-14_lo10
  shutdown: false
  ip_address: 192.168.0.14/32
ethernet_interfaces:
- name: Ethernet1
  peer: H14
  type: routed
  shutdown: false
  mtu: 1500
  vrf: VRF_A
  ip_address: 172.16.14.254/24
- name: Ethernet2
  peer: R1-PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.15.1/24
- name: Ethernet3
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.16.1/24
- name: Ethernet4
  peer: P10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.51.1/24
- name: Ethernet5
  peer: P11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.52.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.14
  neighbors:
    - ip_address: 192.14.15.2
      remote_as:  65102
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.14.16.2
      remote_as:  65103
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.14.15.2
        activate: true
      - ip_address: 192.14.16.2
        activate: true
    networks: 
      - prefix: 192.168.0.14/32
      - prefix: 172.16.14.0/24

