hostname: Edge10
ip_routing: true
vrfs:
- name: VRF_A
  ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Edge-10_l10
  shutdown: false
  ip_address: 192.168.0.10/32
ethernet_interfaces:
- name: Ethernet1
  peer: Edge11
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet2
  peer: Edge11
  type: routed
  shutdown: true
  mtu: 1500
- name: Ethernet3
  peer: Leaf11
  type: routed
  shutdown: false
  mtu: 1500
  vrf: VRF_A
  ip_address: 192.10.31.1/24
  ospf_area: 0
  ospf_network_point_to_point: true
- name: Ethernet4
  peer: R1-PE1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.10.15.1/24
- name: Ethernet5
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.10.16.1/24
router_bgp:
  as: 65000
  router_id: 192.168.0.10
  neighbors:
    - ip_address: 192.10.15.2
      remote_as:  65102
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.10.16.2
      remote_as:  65103
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
        - ip_address: 192.10.15.2
          activate: true
        - ip_address: 192.10.16.2
          activate: true
    networks: 
      - prefix: 192.168.0.10/32

  vrfs:
  - name: VRF_A
    redistribute_routes:
      - source_protocol: connected
      - source_protocol: ospf
  

router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.10
      vrf: VRF_A
      redistribute:
        bgp:

