hostname: H21
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
loopback_interfaces:
 
ethernet_interfaces:
- name: Ethernet1
  peer: Leaf21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.21.45/24
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.21.254
  
