hostname: H24
ip_routing: true
spanning_tree:
  mode: none

ethernet_interfaces:
- name: Ethernet1
  peer: Edge24
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.24.48/24
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 172.16.24.254


