hostname: Leaf11
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Leaf11_lo10
  shutdown: false
  ip_address: 192.168.0.31/32
ethernet_interfaces:
- name: Ethernet1
  peer: H11
  type: routed
  shutdown: false
  mtu: 1500
  ospf_area: 0
  ip_address: 172.16.11.254/24
- name: Ethernet2
  peer: Edge10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.10.31.2/24
  ospf_area: 0
  ospf_network_point_to_point: true
- name: Ethernet3
  peer: Edge11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.31.2/24
- name: Ethernet4
  peer: Edge22
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.12.31.2/24

router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.31
