hostname: R1-PE1
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: R2-PE2_lo10
  shutdown: false
  ip_address: 192.168.0.15/32
ethernet_interfaces:
- name: Ethernet1
  peer: P10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.15.51.1/24
- name: Ethernet2
  peer: P11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.15.52.1/24
- name: Ethernet3
  peer: RR1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.15.71.1/24
- name: Ethernet4
  peer: RR2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.15.72.1/24
- name: Ethernet5
  peer: Edge10
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.10.15.2/24
- name: Ethernet6
  peer: Edge11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.11.15.2/24
- name: Ethernet7
  peer: Edge12
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.12.15.2/24
- name: Ethernet8
  peer: Edge13
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.13.15.2/24
- name: Ethernet9
  peer: Edge14
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.14.15.2/24
router_bgp:
  as: 65102
  router_id: 192.168.0.15
  neighbors:
    - ip_address: 192.10.15.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.11.15.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.12.15.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.13.15.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.14.15.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.15.51.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.15.52.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.15.71.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.15.72.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.10.15.1
        activate: true
      - ip_address: 192.11.15.1
        activate: true
      - ip_address: 192.12.15.1
        activate: true
      - ip_address: 192.13.15.1
        activate: true
      - ip_address: 192.14.15.1
        activate: true
      - ip_address: 192.15.51.2
        activate: true
      - ip_address: 192.15.52.2
        activate: true
      - ip_address: 192.15.71.2
        activate: true
      - ip_address: 192.15.72.2
        activate: true
    networks: 
      - prefix: 192.168.0.15/32
    redistribute_routes:
    - source_protocol: connected