hostname: R2-PE2
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: R2-PE2_lo10
  shutdown: false
  ip_address: 192.168.0.25/32
ethernet_interfaces:
- name: Ethernet1
  peer: P20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.53.1/24
- name: Ethernet2
  peer: P21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.54.1/24
- name: Ethernet3
  peer: RR3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.76.1/24
- name: Ethernet4
  peer: RR4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.77.1/24
- name: Ethernet5
  peer: Edge20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.20.25.2/24
- name: Ethernet6
  peer: Edge21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.21.25.2/24
- name: Ethernet7
  peer: Edge22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.22.25.2/24
- name: Ethernet8
  peer: Edge22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.23.25.2/24
- name: Ethernet9
  peer: Edge24
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.24.25.2/24

router_bgp:
  as: 65202
  router_id: 192.168.0.25
  neighbors:
    - ip_address: 192.20.25.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.21.25.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.22.25.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.23.25.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.24.25.1
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.25.53.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.25.54.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.25.76.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.25.77.2
      remote_as:  65000
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.20.25.1
        activate: true
      - ip_address: 192.21.25.1
        activate: true
      - ip_address: 192.22.25.1
        activate: true
      - ip_address: 192.23.25.1
        activate: true
      - ip_address: 192.24.25.1
        activate: true
      - ip_address: 192.25.53.2
        activate: true
      - ip_address: 192.25.54.2
        activate: true
      - ip_address: 192.25.76.2
        activate: true
      - ip_address: 192.25.77.2
        activate: true
    networks: 
      - prefix: 192.168.0.25/32
    redistribute_routes:
    - source_protocol: connected