hostname: RR1
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: RR1_lo10
  shutdown: false
  ip_address: 192.168.0.71/32
- name: Dps1
  shutdown: false
  ip_address: 71.71.71.71/32
ethernet_interfaces:
  - name: Ethernet1
    peer: RR2
    type: routed
    shutdown: true
    mtu: 1500
    ip_address: 192.71.72.1/24
  - name: Ethernet2
    peer: R1-PE1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 192.15.71.2/24
  - name: Ethernet3
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 192.16.71.2/24
router_bgp:
  as: 65000
  router_id: 192.168.0.71
  neighbors:
    - ip_address: 192.15.71.1
      remote_as:  65102
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.16.71.1
      remote_as:  65103
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.15.71.1
        activate: true
        route_map_out: E2OUT
      - ip_address: 192.16.71.1
        activate: true
        route_map_out: E3OUT
    networks: 
      - prefix: 192.168.0.71/32
prefix_lists:
  - name: E2OUT
    sequence_numbers:
      - sequence: 10
        action: permit 192.15.71.0/24
      - sequence: 20
        action: permit 192.168.0.71/32
  - name: E3OUT
    sequence_numbers:
      - sequence: 10
        action: permit 192.16.71.0/24
      - sequence: 20
        action: permit 192.168.0.71/32

route_maps:
  - name: E2OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list E2OUT
  - name: E3OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list E3OUT


