hostname: RR4
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: RR4_lo10
  shutdown: false
  ip_address: 192.168.0.77/32
ethernet_interfaces:
- name: Ethernet1
  peer: RR3
  type: routed
  shutdown: true
  mtu: 1500
  ip_address: 192.76.77.2/24
- name: Ethernet2
  peer: R2-PE2
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.25.77.2/24
- name: Ethernet3
  peer: ISP-1
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 192.26.77.2/24
router_bgp:
  as: 65000
  router_id: 192.168.0.77
  neighbors:
    - ip_address: 192.25.77.1
      remote_as:  65202
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
    - ip_address: 192.26.77.1
      remote_as:  65203
      allowas_in:
        enabled: true
        # Number of local ASNs allowed in a BGP update.
        times: 6
  address_family_ipv4:
    neighbors:
      - ip_address: 192.25.77.1
        activate: true
        route_map_out: E2OUT 
      - ip_address: 192.26.77.1
        activate: true
        route_map_out: E3OUT 
    networks: 
      - prefix: 192.168.0.77/32


prefix_lists:
  - name: E2OUT
    sequence_numbers:
      - sequence: 10
        action: permit 192.25.77.0/24
      - sequence: 20
        action: permit 192.168.0.77/32
  - name: E3OUT
    sequence_numbers:
      - sequence: 10
        action: permit 192.26.77.0/24
      - sequence: 20
        action: permit 192.168.0.77/32

route_maps:
  - name: E2OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list E2OUT
  - name: E3OUT
    sequence_numbers:
      - sequence: 10
        type: permit
        match:
          - ip address prefix-list E3OUT




