---
- name: Build MPLS Structured Configs
  hosts: MPLS_FABRIC
  tasks:
    - name: Generate AVD Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
- name: Build EOS Config
  hosts: MPLS_FABRIC
  tasks:
    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
- name: Build region configurations
  hosts: REGION1, REGION2, Internet
  vars:
      root_dir: "."
  tasks:
    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
