---
- name: Validate state for Pathfinder
  hosts: PF_NETWORK
  connection: httpapi
  tasks:
    - name: Validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
