---
type: wan_rr

wan_rr:
  defaults:
    data_plane_cpu_allocation_max: 1
    loopback_ipv4_pool: 10.99.101.0/24
    vtep_loopback_ipv4_pool: 10.99.102.0/24
    filter:
      always_include_vrfs_in_tenants: [TENANT_A]
  nodes:
    - name: Pathfinder1
      id: 1
      cv_pathfinder_region: REGION1
      cv_pathfinder_site: SITE1_R1_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 172.16.1.2/24
          wan_carrier: mpls_r1
        - name: Ethernet3
          ip_address: 11.11.1.2/24
          wan_carrier: internet
    - name: Pathfinder2
      id: 2
      cv_pathfinder_region: REGION1
      cv_pathfinder_site: SITE1_R1_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 172.16.2.2/24
          wan_carrier: mpls_r1
        - name: Ethernet3
          ip_address: 11.11.2.2/24
          wan_carrier: internet