---
type: wan_rr

wan_rr:
  defaults:
    data_plane_cpu_allocation_max: 1
    loopback_ipv4_pool: 10.99.101.0/24
    vtep_loopback_ipv4_pool: 10.99.102.0/24
    filter:
      always_include_vrfs_in_tenants: [TENANT_A]
  nodes:
    - name: Pathfinder3
      id: 3
      cv_pathfinder_region: REGION2
      cv_pathfinder_site: SITE1_R2_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 172.16.3.2/24
          wan_carrier: mpls_r2
        - name: Ethernet3
          ip_address: 22.22.3.2/24
          wan_carrier: internet
    - name: Pathfinder4
      id: 4
      cv_pathfinder_region: REGION2
      cv_pathfinder_site: SITE1_R2_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 172.16.4.2/24
          wan_carrier: mpls_r2
        - name: Ethernet3
          ip_address: 22.22.4.2/24
          wan_carrier: internet