---
tenants:
  - name: TENANT_A
    vrfs: 
      - name: VRF_A
        vrf_id: 19
        address_families:
          - vpn-ipv4
        l3_interfaces:
          - description: REGION1
            enabled: true
            interfaces:
              - Ethernet4
              - Ethernet5
              - Ethernet4
              - Ethernet5
            ip_addresses: 
              - 192.51.81.2/24
              - 192.52.81.2/24
              - 192.51.82.2/24
              - 192.52.82.2/24
            nodes: 
              - PE1
              - PE1
              - PE2
              - PE2
          - description: REGION2
            enabled: true
            interfaces:
              - Ethernet4
              - Ethernet5
              - Ethernet4
              - Ethernet5
            ip_addresses: 
              - 192.53.83.2/24
              - 192.54.83.2/24
              - 192.53.84.2/24
              - 192.54.84.2/24
            nodes: 
              - PE3
              - PE3
              - PE4
              - PE4
        bgp_peers:
          - ip_address: 192.51.81.1
            nodes: [PE1]
            remote_as: 65000
          - ip_address: 192.52.81.1
            nodes: [PE1]
            remote_as: 65000
          - ip_address: 192.51.82.1
            nodes: [PE2]
            remote_as: 65000
          - ip_address: 192.52.82.1
            nodes: [PE2]
            remote_as: 65000
          - ip_address: 192.53.83.1
            nodes: [PE3]
            remote_as: 65000
          - ip_address: 192.54.83.1
            nodes: [PE3]
            remote_as: 65000
          - ip_address: 192.53.84.1
            nodes: [PE4]
            remote_as: 65000
          - ip_address: 192.54.84.1
            nodes: [PE4]
            remote_as: 65000