---
type: wan_rr

wan_rr:
  defaults:
    cv_pathfinder_transit_mode: "region"
    data_plane_cpu_allocation_max: 1
    loopback_ipv4_pool: 10.99.101.0/24
    vtep_loopback_ipv4_pool: 10.99.102.0/24
    filter:
      always_include_vrfs_in_tenants: [TENANT_A]
  nodes:
    - name: RR1
      id: 1
      cv_pathfinder_region: REGION1
      cv_pathfinder_site:   SITE1_R1_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.15.71.2/24
          wan_carrier: mpls
        - name: Ethernet3
          ip_address: 192.16.71.2/24
          wan_carrier: internet
    - name: RR2
      id: 2
      cv_pathfinder_region: REGION1
      cv_pathfinder_site:   SITE1_R1_PF
      l3_interfaces:
        - name: Ethernet2
          ip_address: 192.15.72.2/24
          wan_carrier: mpls
        - name: Ethernet3
          ip_address: 192.16.72.2/24
          wan_carrier: internet
