---
- name: Build config
  hosts: PF_NETWORK
  connection: local
  gather_facts: false
  tasks:

    - name: Generate intended variables
      ansible.builtin.import_role:
        name: arista.avd.eos_designs

    - name: Generate intended config and documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
