- name: Configuration deployment to CVaaS
  hosts: PF_NETWORK # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: www.cv-prod-us-central1-c.arista.io
        cv_run_change_control: true
        cv_token: "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjcyMzEyODYwODY2NTAxODA2NDUsImRzbiI6ImFuc2libGUiLCJkc3QiOiJhY2NvdW50IiwiZXhwIjoxNzU0MTU4OTk2LCJpYXQiOjE3MzE2MTIyMDAsIm9naSI6NzIzMTI4NjA4NjY1MDE3NDUyMywib2duIjoicGF0aGZpbmRlci0yMCIsInNpZCI6IjdkNTBjMDhkNTc1OWY0MzNiNjE1ZmM5ODBiNjhjOTI2MDcwMzU5OTY2OWRkNmFmZTljYThlN2U3OWVmZjc0MjItVG5WN2wzV25vZEZZWlRoU3NrQzY2UDNJMnpLWk01Yk1hYUNlQTVrQiJ9.iK_SQLs667p3o6XEoRIiVw06cfOVJXLg-oGBQgCKEEn_cmxT8tTVx7p7LS14FFRc-Sb-gvoegkWkUGXSajwZLg"