hostname: Edge23
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
  - name: Loopback10
    description: Edge-23_lo10
    shutdown: false
    ip_address: 192.168.0.23/32



ethernet_interfaces:
# LAN

  - name: Ethernet1
    peer: H23
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 10.2.23.1/24

  - name: Ethernet2
    peer: R2-PE2
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.16.23.2/24

router_bgp:
  as: 65000
  router_id: 192.168.0.23
  neighbors:
    - ip_address: 172.16.23.1
      remote_as:  65202
  address_family_ipv4:
    neighbors:
      - ip_address: 172.16.23.1
        activate: true
  redistribute_routes:
    - source_protocol: connected
