hostname: Edge14
ip_routing: true
spanning_tree:
  mode: none
vrfs:
  - name: VRF_A
    ip_routing: true
loopback_interfaces:
  - name: Loopback10
    description: Edge-14_lo10
    shutdown: false
    ip_address: 192.168.0.14/32

# LAN
ethernet_interfaces:
  - name: Ethernet1
    peer: H14
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 10.1.14.1/24

# WAN
  - name: Ethernet2
    ip_address: 172.16.14.2/24
    peer: R1-PE1
    type: routed
    shutdown: false
    mtu: 1500
  - name: Ethernet3
    ip_address: 11.11.14.2/24
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    
router_bgp:
  as: 65000
  router_id: 192.168.0.14
  neighbors:
    - ip_address: 172.16.14.1
      remote_as:  65102
      description: R1_MPLS
    - ip_address: 11.11.14.1
      remote_as:  65103
      description: ISP-1
  address_family_ipv4:
    neighbors:
      - ip_address: 172.16.14.1
        activate: true
      - ip_address: 11.11.14.1
        activate: true
  redistribute_routes:
    - source_protocol: connected
