hostname: Edge13
ip_routing: true
spanning_tree:
  mode: none
vrfs:
  - name: VRF_A
    ip_routing: true
    
loopback_interfaces:
  - name: Loopback10
    description: Edge-13_lo10
    shutdown: false
    ip_address: 192.168.0.13/32

ethernet_interfaces:
# LAN  
  - name: Ethernet1
    peer: H13
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 10.1.13.1/24

# WAN
  - name: Ethernet2
    peer: R1-PE1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.16.13.2/24
  - name: Ethernet3
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 11.11.13.2/24

router_bgp:
  as: 65000
  router_id: 192.168.0.13
  neighbors:
    - ip_address: 172.16.13.1
      remote_as:  65102
    - ip_address: 11.11.13.1
      remote_as:  65103
  address_family_ipv4:
    neighbors:
      - ip_address: 172.16.13.1
        activate: true
      - ip_address: 11.11.13.1
        activate: true
  redistribute_routes:
    - source_protocol: connected
