hostname: Edge10
ip_routing: true
spanning_tree:
  mode: none

vrfs:
- name: VRF_A
  ip_routing: true

loopback_interfaces:
  - name: Loopback10
    description: Edge-10_l10
    shutdown: false
    ip_address: 192.168.0.10/32

ethernet_interfaces:
# Shut down interlinks
  - name: Ethernet1
    peer: Edge11
    type: routed
    shutdown: true
  - name: Ethernet2
    peer: Edge11
    type: routed
    shutdown: true

# LAN
  - name: Ethernet3
    peer: Leaf11
    type: routed
    shutdown: false
    mtu: 1500
    vrf: VRF_A
    ip_address: 10.251.10.1/24
    ospf_area: 0
    ospf_network_point_to_point: true

# WAN Connections

  - name: Ethernet4
    peer: R1-PE1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.16.10.2/24
  - name: Ethernet5
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 11.11.10.2/24





router_bgp:
  as: 65000
  router_id: 192.168.0.10
  neighbors:
    - ip_address: 172.16.10.1
      remote_as:  65102
      description: R1_MPLS
    - ip_address: 11.11.10.1
      remote_as:  65103
      description: ISP-1
  address_family_ipv4:
    neighbors:
        - ip_address: 172.16.10.1
          activate: true
          prefix_list_out: MPLS_OUT
        - ip_address: 11.11.10.1
          activate: true
          route_map_out: INTERNET_OUT

    redistribute_routes:
      - source_protocol: connected
  vrfs:
    - name: VRF_A
      redistribute_routes:
        - source_protocol: connected
        - source_protocol: ospf


router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.10
      default_information_originate:
        always: true
      vrf: VRF_A
      redistribute:
        bgp:


      