hostname: Edge11
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
  - name: Loopback10
    description: Edge-11_lo10
    shutdown: false
    ip_address: 192.168.0.11/32
ethernet_interfaces:
  - name: Ethernet1
    peer: Edge11
    type: routed
    shutdown: true
  - name: Ethernet2
    peer: Edge11
    type: routed
    shutdown: true
  - name: Ethernet3
    peer: Leaf11
    type: routed
    shutdown: true
  - name: Ethernet4
    peer: R1-PE1
    type: routed
    shutdown: true
  - name: Ethernet5
    peer: ISP-1
    type: routed
    shutdown: true
  - name: Ethernet6
    peer: Leaf12
    type: routed
    shutdown: true

      