hostname: Edge20
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
  ip_routing: true
loopback_interfaces:
  - name: Loopback10
    description: Edge-20_lo10
    shutdown: false
    ip_address: 192.168.0.20/32
ethernet_interfaces:
# Shut down interlinks

  - name: Ethernet1
    peer: Edge20
    type: routed
    shutdown: true
    mtu: 1500
  - name: Ethernet2
    peer: Edge20
    type: routed
    shutdown: true
    mtu: 1500

# LAN

  - name: Ethernet3
    peer: Leaf21
    type: routed
    shutdown: false
    mtu: 
    vrf: VRF_A
    ip_address: 10.252.20.1/24
    ospf_area: 0
    ospf_network_point_to_point: true

# WAN Connections

  - name: Ethernet4
    peer: R1-PE1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.16.10.2/24

  - name: Ethernet5
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: dhcp

router_bgp:
  as: 65000
  router_id: 192.168.0.20
  neighbors:
    - ip_address: 172.16.20.1
      remote_as:  65202
      description: R2-PE2
  address_family_ipv4:
    neighbors:
      - ip_address: 172.16.20.1
        activate: true
  redistribute_routes:
    - source_protocol: connected
  vrfs:
    - name: VRF_A
      redistribute_routes:
        - source_protocol: connected
        - source_protocol: ospf


router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.20
      vrf: VRF_A
      redistribute:
        static:
      default_information_originate:
        always: true