hostname: H11
ip_routing: true
spanning_tree:
  mode: none
ethernet_interfaces:
- name: Ethernet1
  peer: Leaf11
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.1.10.11/24
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.1.10.1
# Turn on Telnet just to test traffic
eos_cli: |-
    management telnet
      no shutdown
