hostname: H21
ip_routing: true
spanning_tree:
  mode: none
vrfs:
- name: VRF_A
loopback_interfaces:
 
ethernet_interfaces:
- name: Ethernet1
  peer: Leaf21
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.2.20.21/24
static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 10.2.20.1
  
# Turn on Telnet just to test traffic
eos_cli: |-
    management telnet
      no shutdown
