hostname: Leaf12
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
  - name: Loopback10
    description: Leaf12_lo10
    shutdown: false
    ip_address: 192.168.0.32/32
ethernet_interfaces:
# LAN
  - name: Ethernet1
    peer: H12
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 10.1.12.1/24

    ospf_area: 0
  - name: Ethernet2
    peer: Edge12
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 10.251.12.2/24
    ospf_area: 0
    ospf_network_point_to_point: true


router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.32
      default_information_originate:
        always: true