hostname: Leaf21
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: Leaf21_lo10
  shutdown: false
  ip_address: 192.168.0.33/32
ethernet_interfaces:
# LAN Connections

- name: Ethernet1
  peer: H21
  type: routed
  shutdown: false
  mtu: 1500
  ospf_area: 0
  ip_address: 10.2.20.1/24

# To WAN

- name: Ethernet2
  peer: Edge20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 10.252.20.2/24
  ospf_area: 0
  ospf_network_point_to_point: true


router_ospf:
  process_ids:
    - id: 10
      router_id: 192.168.0.33
      redistribute: 
        bgp: