custom_hostname: P6
custom_router_isis:
  instance: CORE
  segment_routing_mpls:
    enabled: true
    router_id: 192.168.0.101.6
  eos_cli: |-
    traffic-engineering
      no shutdown
      is-type level-1
custom_ethernet_interfaces:
  - name: Ethernet1
    eos_cli: |-
      traffic-engineering
  - name: Ethernet2
    eos_cli: |-
      traffic-engineering
  - name: Ethernet3
    eos_cli: |-
      traffic-engineering
  - name: Ethernet4
    eos_cli: |-
        traffic-engineering
  - name: Ethernet5
    eos_cli: |-
        traffic-engineering
custom_router_traffic_engineering:
  #enabled: true
  segment_routing:
  router_id:
    ipv4: 192.168.101.6
