hostname: Pathfinder4
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
  - name: Loopback10
    description: RR4_lo10
    shutdown: false
    ip_address: 192.168.0.77/32
ethernet_interfaces:
  - name: Ethernet1
    peer: Pathfinder4
    type: routed
    shutdown: true
    mtu: 1500
  - name: Ethernet2
    peer: R2-PE2
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 172.16.4.2/24
  - name: Ethernet3
    peer: ISP-1
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 22.22.4.2/24


static_routes:
  - vrf: default
    destination_address_prefix: 0.0.0.0/0
    gateway: 22.22.4.1
  - vrf: default
    destination_address_prefix: 172.16.0.0/12
    gateway: 172.16.4.1