hostname: R2-PE2
ip_routing: true
spanning_tree:
  mode: none
loopback_interfaces:
- name: Loopback10
  description: R2-PE2_lo10
  shutdown: false
  ip_address: 192.168.0.25/32
ethernet_interfaces:
- name: Ethernet1
  peer: Transit3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.53.1/24
- name: Ethernet2
  peer: Transit4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.54.1/24
- name: Ethernet3
  peer: Pathfinder3
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.3.1/24
- name: Ethernet4
  peer: Pathfinder4
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.4.1/24
- name: Ethernet5
  peer: Edge20
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.20.1/24
- name: Ethernet6
  peer: Edge21
  type: routed
  shutdown: true
- name: Ethernet7
  peer: Edge22
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.22.1/24
- name: Ethernet8
  peer: Edge23
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.23.1/24
- name: Ethernet9
  peer: Edge24
  type: routed
  shutdown: false
  mtu: 1500
  ip_address: 172.16.24.1/24

router_bgp:
  as: 65202
  router_id: 192.168.0.25
  neighbors:
    - ip_address: 172.16.20.2
      remote_as:  65000
      description: Edge20
    - ip_address: 172.16.22.2
      description: Edge22
      remote_as:  65000
    - ip_address: 172.16.23.2
      description: Edge23
      remote_as:  65000
    - ip_address: 172.16.24.2
      description: Edge24
      remote_as:  65000
  address_family_ipv4:
    neighbors:
      - ip_address: 172.16.20.2
        activate: true
        prefix_list_in: MPLS_IN
      - ip_address: 172.16.22.2
        activate: true
        prefix_list_in: MPLS_IN
      - ip_address: 172.16.23.2
        activate: true
        prefix_list_in: MPLS_IN
      - ip_address: 172.16.24.2
        activate: true
        prefix_list_in: MPLS_IN
    redistribute_routes:
    - source_protocol: connected

  
prefix_lists:
  - name: MPLS_IN
    sequence_numbers:
      - sequence: 10
        action: permit 172.16.0.0/16 eq 24